name: Check

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    tests:
        strategy:
            matrix:
                include:
                    -   platform-version: 261
                        platform-type: RR
                        java-version: 21
                    -   platform-version: 261
                        platform-type: PY
                        java-version: 21
                    -   platform-version: 262
                        platform-type: IU
                        java-version: 25

        runs-on: ubuntu-latest
        env:
            ORG_GRADLE_PROJECT_shortPlatformVersion: ${{ matrix.platform-version }}
            ORG_GRADLE_PROJECT_platformType: ${{ matrix.platform-type }}
            CI: 1

        steps:
            -   uses: actions/checkout@v6

            -   name: Set up JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'corretto'
                    java-version: ${{ matrix.java-version }}

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v6

            -   name: Download dependencies
                run: ./gradlew dependencies --stacktrace --configuration=intellijPlatformTestClasspath

            -   name: Regenerate lexer and parser
                run: ./gradlew generateLexer generateParser --rerun-tasks --stacktrace

            -   name: Build
                run: ./gradlew assemble --stacktrace -Pkotlin.incremental=false

            -   name: Tests
                run: ./gradlew test --stacktrace -Pkotlin.incremental=false

            -   name: Verify plugin.xml
                run: ./gradlew verifyPluginConfiguration

            -   name: Verify plugin
                if: ${{ matrix.platform-type == 'PY' }}
                run: ./gradlew verifyPlugin


