name: Publish stable version to the Marketplace

on:
    release:
        types: [released]

jobs:
    publish-release:
        strategy:
            matrix:
                include:
                - gradle-properties-version: 261
                  java-version: 21
                - gradle-properties-version: 262
                  java-version: 25

        runs-on: ubuntu-latest
        env:
            ORG_GRADLE_PROJECT_shortPlatformVersion: ${{ matrix.gradle-properties-version }}
            JB_PUB_TOKEN: ${{ secrets.JB_PUB_TOKEN }}

        steps:
            -   uses: actions/checkout@v6

            -   name: Set up JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'corretto'
                    java-version: ${{ matrix.java-version }}

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v6

            -   name: Regenerate lexer and parser
                run: ./gradlew generateLexer generateParser --rerun-tasks --stacktrace

            -   name: Publish plugin
                run: ./gradlew publishPlugin --stacktrace -Pkotlin.incremental=false



